### ISSUE TITLE
Срочно построить дом по координатам 37 22 -99

### ISSUE THREAD

**Issue by ProCompTEAM** [ProCompTEAM/MCRPG#4]
Срочно построить дом по координатам 37 22 -99

![PARK_MAIN](https://user-images.githubusercontent.com/24737193/71644708-e899a780-2cdd-11ea-84d3-5c6ddabd5965.jpg)

**Comment by FirzMob** [comment]
Готово, сэр

**Comment by FirzMob** [comment]
ю

**Comment by StormLVV** [comment]
Та а шо строить то?
